# Generated by Django 3.2.4 on 2021-11-14 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addemp_id', models.CharField(max_length=50)),
                ('addemail', models.CharField(max_length=50)),
                ('addname', models.CharField(max_length=50)),
                ('addDepartment', models.CharField(max_length=50)),
                ('addsection', models.CharField(max_length=50)),
                ('addrole', models.CharField(max_length=50)),
                ('addtraining', models.CharField(max_length=50)),
                ('addphone', models.CharField(max_length=50)),
                ('addpassword1', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AssignInvestigator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_id', models.CharField(max_length=50)),
                ('nameassignedinvestigator', models.CharField(max_length=50)),
                ('emailassignedinvestigator', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FinalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reinc_id', models.CharField(max_length=50)),
                ('sum', models.CharField(max_length=500)),
                ('img', models.CharField(max_length=500)),
                ('rca', models.CharField(max_length=500)),
                ('imc', models.CharField(max_length=500)),
                ('rtc', models.CharField(max_length=500)),
                ('ca', models.CharField(max_length=500)),
                ('cap', models.CharField(max_length=500)),
                ('cad', models.DateField(max_length=500)),
                ('pa', models.CharField(max_length=500)),
                ('pap', models.CharField(max_length=500)),
                ('pat', models.DateField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='IncidentReporting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datereport', models.CharField(max_length=50)),
                ('timereport', models.CharField(max_length=50)),
                ('dateincident', models.CharField(max_length=50)),
                ('reportedby', models.CharField(max_length=50)),
                ('incident_id', models.CharField(max_length=50)),
                ('timeincident', models.CharField(max_length=50)),
                ('locationincident', models.CharField(max_length=50)),
                ('incidentdesc', models.CharField(max_length=50)),
                ('incidentaction', models.CharField(max_length=50)),
                ('victimname', models.CharField(max_length=50)),
                ('victimrole', models.CharField(max_length=50)),
                ('victimemp_id', models.CharField(max_length=50)),
                ('victimcon_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SpecialAnalyzing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speinc_id', models.CharField(max_length=50)),
                ('speicua', models.CharField(max_length=500)),
                ('speicuc', models.CharField(max_length=500)),
                ('sperchf', models.CharField(max_length=500)),
                ('spercof', models.CharField(max_length=500)),
                ('icuao', models.CharField(max_length=500)),
                ('icuco', models.CharField(max_length=500)),
                ('rchfo', models.CharField(max_length=500)),
                ('rcofo', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='WhyWhyAnalyzing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whyinc_id', models.CharField(max_length=50)),
                ('ps', models.CharField(max_length=500)),
                ('why1', models.CharField(max_length=200)),
                ('why2', models.CharField(max_length=200)),
                ('why3', models.CharField(max_length=200)),
                ('why4', models.CharField(max_length=200)),
                ('why5', models.CharField(max_length=200)),
                ('rc', models.CharField(max_length=500)),
            ],
        ),
    ]
