# Generated by Django 4.0 on 2022-01-02 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adduser',
            fields=[
                ('addemp_id', models.IntegerField(primary_key=True, serialize=False)),
                ('addemail', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=100)),
                ('addname', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50)),
                ('adddepartment', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='addDepartment', max_length=100)),
                ('addsection', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=100)),
                ('addrole', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=100)),
                ('addtraining', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=25)),
                ('addphone', models.DecimalField(decimal_places=0, max_digits=15)),
                ('addpassword', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=25)),
            ],
            options={
                'db_table': 'adduser',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Assigninvestigator',
            fields=[
                ('incident_id', models.IntegerField(db_column='Incident_id', primary_key=True, serialize=False)),
                ('nameassignedinvestigator', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50)),
                ('emailassignedinvestigator', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=100)),
            ],
            options={
                'db_table': 'assigninvestigator',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Incidentreporting',
            fields=[
                ('datereport', models.DateField()),
                ('timereport', models.TimeField()),
                ('reportedby', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50)),
                ('dateincident', models.DateField()),
                ('timeincident', models.TimeField()),
                ('locationincident', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50)),
                ('incidentdesc', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=1000)),
                ('incidentaction', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=1000)),
                ('victimname', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50)),
                ('victimrole', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=100)),
                ('victimemp_id', models.IntegerField(primary_key=True, serialize=False)),
                ('victimcon_id', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=100)),
                ('assign_inv_email', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=100)),
            ],
            options={
                'db_table': 'incidentreporting',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Actionclosure',
            fields=[
                ('actionclose_inc', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='incidentmanagementapp.assigninvestigator')),
                ('actiondonebyname', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=100)),
                ('actiontaken', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=1000)),
                ('completiondate', models.DateField()),
            ],
            options={
                'db_table': 'actionclosure',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Finalreport',
            fields=[
                ('reinc', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='incidentmanagementapp.assigninvestigator')),
                ('inc_type', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=200)),
                ('summary', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=100)),
                ('img', models.BinaryField(max_length='max')),
                ('rca', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50)),
                ('imc', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=100)),
                ('rtc', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=100)),
                ('ca', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=100)),
                ('cap', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=100)),
                ('cad', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=100)),
                ('pa', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=200)),
                ('pap', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=200)),
                ('pat', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=200)),
                ('intensity', models.IntegerField()),
            ],
            options={
                'db_table': 'finalreport',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Specialanalyzing',
            fields=[
                ('spe_inc', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='incidentmanagementapp.assigninvestigator')),
                ('imm_cause_unsafe_ac', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=100)),
                ('imm_cause_unsafe_con', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=100)),
                ('root_cause_human_fac', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=100)),
                ('root_cause_org_fac', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=100)),
            ],
            options={
                'db_table': 'specialanalyzing',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Verifyactionclose',
            fields=[
                ('ver_action_close_inc', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='incidentmanagementapp.assigninvestigator')),
                ('inc_closeoropen', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=10)),
                ('remarks', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=500)),
            ],
            options={
                'db_table': 'verifyactionclose',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Whywhyanalyzing',
            fields=[
                ('whyinc', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='incidentmanagementapp.assigninvestigator')),
                ('ps', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=100)),
                ('why1', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=100)),
                ('why2', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=100)),
                ('why3', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=100)),
                ('why4', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=100)),
                ('why5', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=100)),
                ('rc', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=100)),
            ],
            options={
                'db_table': 'whywhyanalyzing',
                'managed': False,
            },
        ),
    ]
